### ISSUE TITLE
Select term window after creating

### ISSUE THREAD

**Issue by willmcclellan** [IvanMalison/term-manager#4]
Thanks for creating this, it's perfect for my workflow. The only niggle is it doesn't select the term window after creating it, what's the best way to do that?

**Comment by colonelpanic8** [comment]
by select do you mean make the active buffer?

**Comment by colonelpanic8** [comment]
The function that is called to display the term buffer is `term-manager-display-buffer'

https://github.com/IvanMalison/term-manager/blob/7180f09078f89aadb83061420ca8fd58d929b629/term-manager.el#L46

You can customize the variable `term-manager-display-buffer-alist` to control how the window is displayed

See this infor about display-buffer

https://www.gnu.org/software/emacs/manual/html_node/elisp/Choosing-Window.html

**Comment by willmcclellan** [comment]
> by select do you mean make the active buffer?

@IvanMalison Yeh that's it. I use a keybinding to open a term from anywhere and make it the active buffer. `term-manager-display-buffer-alist` looks useful for how it splits, but it still doesn't make it the active buffer. Unless I'm missing something with display-buffer

**Comment by colonelpanic8** [comment]
@willmcclellan  Yeah, I guess this was never an issue for me because i display the terminal in the current buffer/frame. I'm assuming you've configured things so that it opens in a different frame/buffer. Anyway, this should be fixed with f4291ea. Let me know if that does the trick.

**Comment by willmcclellan** [comment]
That works, thanks for taking a look so quickly 👍
